#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 13 13:05:14 2016

@author: guillaume
"""

#%%
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
#%%
# import the data
df = pd.read_pickle('metrics_dataset.pickle')


#%%
#cross-validation split
X = np.array(df.drop(['Survived'], axis = 1))
y = np.array(df['Survived'])
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

#%%
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_log = logreg.predict_proba(X_test)

#%% 
